# pyright: strict
from enum import Enum, auto

class FeatureType(Enum):
    FEATURE_ICE = auto()
    FEATURE_JUNGLE = auto()
    FEATURE_MARSH = auto()
    FEATURE_OASIS = auto()
    FEATURE_FLOOD_PLAINS = auto()
    FEATURE_FOREST = auto()
    FEATURE_FALLOUT = auto()
    FEATURE_CRATER = auto()
    FEATURE_FUJI = auto()
    FEATURE_MESA = auto()
    FEATURE_REEF = auto()
    FEATURE_VOLCANO = auto()
    FEATURE_GIBRALTAR = auto()
    FEATURE_GEYSER = auto()
    FEATURE_FOUNTAIN_YOUTH = auto()
    FEATURE_POTOSI = auto()
    FEATURE_EL_DORADO = auto()
    FEATURE_ATOLL = auto()
    FEATURE_SRI_PADA = auto()
    FEATURE_MT_SINAI = auto()
    FEATURE_MT_KAILASH = auto()
    FEATURE_ULURU = auto()
    FEATURE_LAKE_VICTORIA = auto()
    FEATURE_KILIMANJARO = auto()
    FEATURE_SOLOMONS_MINE = auto()
    NONE = auto()