

from enum import Enum, auto


class ImprovementType(Enum):
    NONE = auto()
    IMPROVEMENT_FARM = auto()
    IMPROVEMENT_MINE = auto()
    IMPROVEMENT_LUMBERMILL = auto()
    IMPROVEMENT_QUARRY = auto()
    IMPROVEMENT_PASTURE = auto()
    IMPROVEMENT_CAMP = auto()
    IMPROVEMENT_TRADING_POST = auto()
    IMPROVEMENT_FISHING_BOATS = auto()
    IMPROVEMENT_PLANTATION = auto()
    IMPROVEMENT_WELL = auto()
    IMPROVEMENT_OFFSHORE_PLATFORM = auto()
    IMPROVEMENT_CUSTOMS_HOUSE = auto()
    IMPROVEMENT_ACADEMY = auto()
    IMPROVEMENT_CITADEL = auto()
    IMPROVEMENT_MANUFACTORY = auto()
    IMPROVEMENT_ARCHAEOLOGICAL_DIG = auto()
